<a href="https://colab.research.google.com/github/ttuyetdinh/diveintocode-ml/blob/master/Week%204/Assign15_Uoo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem1

In [81]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
import math

In [82]:
# These are classes that i have used in previous assignments
svr = SVR()
tree = DecisionTreeRegressor()
forest = RandomForestRegressor()
reg = LinearRegression()
scaler = StandardScaler()
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
sr = pd.Series()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


#Problem 2


In [83]:
# In Class DataFrame(), we have:
# Some attribute or variable:
df.shape
df.size
df.index
df. columns
df.style
# Some method:
df.abs()
df.describe()
df.copy()
df.head()
df.isnull()

col1   col2
0  False  False
1  False  False

#Problem 3

In [84]:
class ScratchStandardScaler():
    """

    Attributes
    ----------
    mean_ :ndarray, shape(n_features,)

    var_ :ndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)

        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)
    def transform(self, X):
        """
        fit
        Parameters
        ----------
        X :ndarray, shape (n_samples, n_features)

        Returns
        ----------
        X_scaled :ndarray, shape (n_samples, n_features)
        """
        X_scaled=np.zeros(X.shape)
        for i in range(X.shape[1]):
          for j in range(X.shape[0]):
              X_scaled[j][i]= (X[j][i]-self.mean_[i])/math.sqrt(self.var_[i])
        pass
        return X_scaled

In [85]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print(X)
print("Mean: {}".format(scratch_scaler.mean_[0]))
print("Var : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Mean: 4.859999999999999
Var : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


#Problem 4

In [86]:
class ExampleClass():
    def __init__(self, value):
      try:
        self.value = float(value)
        print("Initial value: {}".format(self.value))
      except:
        print('Not suitable data type')

    def add(self, param = 0):
      self.calculate(param,1)

    def minus(self, param = 0):
      self.calculate(param,2)
      
    def divide(self, param = 1):
     self.calculate(param,3)

    def multi(self, param = 1):
      self.calculate(param,4)

    def calculate(self, param, mode):
      try:
        if mode==1: # +
           self.value += param
        elif mode==2:# -
          self.value -= param
        elif mode==3: # /
          if (param == 0):
              print('Can divide zero !!')
          else:
              self.value /=param
        elif mode==4: # *
           self.value *= param
      except:
        print("Not suitable data type")   
              
example = ExampleClass(5)
example.add([1,2,3])
print("1value : {}".format(example.value))
example.minus(2)
print("2value : {}".format(example.value))
example.divide(2)
print("3value : {}".format(example.value))
example.multi(3)
print("4value : {}".format(example.value))

Initial value: 5.0
Not suitable data type
1value : 5.0
2value : 3.0
3value : 1.5
4value : 4.5
